### ISSUE TITLE
Minor change to section-bibs-level

### ISSUE THREAD

**Issue by June-Skeeter** [pandoc-ext/section-bibliographies#8]
This package is great.  I'm using it to format my CV.  I noticed the `section-bibs-level` parameter wasn't working for me,   Regardless of what value I set for section-bibs-level, it all refs were assigned to the top level headers.

I fixed it for my use case (wanting citations to follow second level headers) making a small change

```
  if not header or section_refs_level < header.level then
    -- Don't do anything for lower level sections.
    return nil
  elseif section_refs_level == header.level then
    blocks = div.content
    subsections = pandoc.List:new{}
``` 

I edited changed the < in line 78 to > & the == in line 81 to <

 ```
  if not header or section_refs_level > header.level then
    -- Don't do anything for lower level sections.
    return nil
  elseif section_refs_level < header.level then
    blocks = div.content
    subsections = pandoc.List:new{}
```

This might break things in other use cases, so theres probably a better fix for this issue.

**Comment by tarleb** [comment]
Thank you! Could you give a short example for me to see how you are using the filter and why the change improves it? I'm not sure I understand what's going on.

**Comment by ttalVlatt** [comment]
Hi there! Agreed, thanks for this awesome package! I also ran into a similar issue making a cv. The .lua modifications @June-Skeeter suggested did make the references appear where I wanted them to, but then it also spits out a full bibliography at the end as well. I've made a repex of the original issue and the modified solution
[quarto-section-bibs-repex.zip](https://github.com/pandoc-ext/section-bibliographies/files/11400571/quarto-section-bibs-repex.zip)

**Comment by ttalVlatt** [comment]
FYI for anyone who finds this useful, I was playing around and comparing my cv.qmd to june-skeeter's CV.qmd, and I realized the strange glitch I was getting where the full bib appeared at the bottom of the doc went away when I put a level-1 header as at the start of the publications section (i.e. `# Publications -> #### Peer Reviewed`), followed by the set heading levels for the sub-bibliographies, (rather than, `## Publications -> #### Peer Reviewed`). Thanks @June-Skeeter for the fix and @tarleb extension!

**Comment by tarleb** [comment]
I've added a `minlevel` option. I believe that it should be sufficient to resolve this, please reopen if this isn't true.
